### ISSUE TITLE
Documentation of `simulate_covid` invites the audience to bring their own interpretation to the work a bit too much

### ISSUE THREAD

**Issue by HughParsonage** [grattan/covidReff#8]
## Clarify the expected result

Bit too minimal: 
```
#' @return A \code{tibble} object.
```

## params rely on the name

The names look good but the description only provides the default. Specify:

1. The object type and length
2. The range of acceptable values, including the interaction with other params.
3. The meaning.
4. An example value and what it would mean.

Note some of the documentation will require `\code{}` when underscores are used.

**Comment by wfmackey** [comment]
Documentation added in https://github.com/grattan/covidReff/commit/62e9cc2c61a017362bfbd5f59f729ad448924485
